name: hydromt-wflow

channels:
  - conda-forge

dependencies:
  - cartopy # to run examples
  - descartes # to run examples
  - hydromt_wflow>=0.2.1
  - jupyterlab # to run examples
  - matplotlib # to run examples
  - pcraster # optional
  - pip  # required for pip-installed deps below
  - pip:
    - hydroengine  # optional

